### ISSUE TITLE
OpenFileDialog crashes on macOs 16

### ISSUE THREAD

**Issue by arnesahlberg** [fsprojects/Avalonia.FuncUI#228]
When I want to use an OpenFileDialog the program crashes. The same code worked with macOs 15, but with 16 I get

`+[CATransaction synchronize] called within transaction`

printed in the terminal and an error reporting window. Some of the contents is:

```
Crashed Thread:        10  Dispatch queue: com.apple.NSXPCConnection.user.endpoint.NSRemoteView.NSOpenPanelService

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [77735]
```

My code for opening the dialog is:
```
let openFile window (state : IWritable<ViewModel>) =

    let dialog = 
        new OpenFileDialog(
            AllowMultiple = false,
            Title = "Select file"
        )
        in

    task {
        let! files = 
            dialog.ShowAsync window 
            in
        let file = files |> Seq.tryHead in
        match file with
        | Some file -> 
            let doc = ViewModel.handleFile file in
            state.Set doc
        | None -> ()
    } |> ignore
```

Is there something I should be doing differently? As I said, the code worked before upgrading to macOs 16, and it works fine on Windows.

**Comment by JaggerJo** [comment]
Running it on the UI Thread should fix this.

https://github.com/fsprojects/Avalonia.FuncUI/issues/190

http://reference.avaloniaui.net/api/Avalonia.Threading/Dispatcher/

**Comment by arnesahlberg** [comment]
Thanks. I've tried, but it's still not working out for me.

I'm not sure I know how to use the dispatcher correctly. What I'm doing now is

```
let openFile window (state : IWritable<ViewModel>) =
    
    let openFileTask = 
        Dispatcher.UIThread.InvokeAsync(fun () ->
            System.Func<System.Threading.Tasks.Task<string[]>>(fun () ->
                let dialog = OpenFileDialog() in
                dialog.AllowMultiple <- false;
                dialog.Title <- "Select document" ;
                dialog.ShowAsync window
            ))
        in

    task {
        let! filesFunc = 
            openFileTask 
            |> Async.AwaitTask
            in
        let! files = 
            filesFunc.Invoke()  
            |> Async.AwaitTask
            in
        match files |> Array.tryHead with
        | Some file -> 
            let doc = ViewModel.LoadFile file in
            state.Set doc
        | None -> ()
    } |> ignore
```
